<a href="https://colab.research.google.com/github/Francisco2963/NumPy/blob/main/An%C3%A1lisis_de_datos_con_Numpy_(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de Datos con NumPy (Core)


**Instrucciones:**

Descripción del Problema: Imagina que estás trabajando como analista de datos para una empresa que recopila información sobre las ventas diarias de diferentes productos en varias tiendas. Necesitas analizar estos datos para extraer información útil y presentar un resumen de las ventas.

**Requisitos del Sistema:**

El programa debe generar datos de ventas de manera aleatoria para 10 productos diferentes en 5 tiendas distintas durante 7 días (una semana).

Los datos deben estar almacenados en un array de NumPy de 3 dimensiones (productos, tiendas, días).

**Debes calcular y mostrar la siguiente información:**

Total de ventas por producto a lo largo de la semana.

Total de ventas por tienda a lo largo de la semana.

Promedio de ventas por producto por día.

Promedio de ventas por tienda por día.

Producto con mayor y menor ventas totales en la semana.

Tienda con mayor y menor ventas totales en la semana.

**Detalles Específicos:**

Genera los datos de ventas aleatorias usando np.random.randint, con valores entre 0 y 100.

Usa funciones de NumPy para calcular las sumas y promedios.

Maneja posibles errores o valores inesperados.

Presenta los resultados de manera clara y estructurada.

**Consideraciones Adicionales:**

Organiza tu código utilizando funciones para cada una de las tareas principales.
Usa comentarios para explicar cada sección de tu código.

Asegúrate de que el código sea robusto y maneje casos en los que los datos generados puedan estar fuera de los rangos esperados

In [5]:
import numpy as np


In [6]:
def generar_datos_ventas(productos, tiendas, dias):
    generar_datos_ventas = np.random.randint(0, 101, (productos, tiendas, dias))
   # Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
    return np.random.randint(0, 101, (productos, tiendas, dias))

In [7]:
def calcular_totales_ventas_por_producto(datos):
    calcular_totales_ventas_por_producto = np.sum(datos, axis=(1, 2))
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

In [8]:
def calcular_totales_ventas_por_tienda(datos):
    calcular_totales_ventas_por_tienda = np.sum(datos, axis=(0, 2))
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

In [9]:
def calcular_promedio_ventas_por_producto(datos):
    calcular_promedio_ventas_por_producto = np.mean(datos, axis=(1, 2))
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

In [10]:
def calcular_promedio_ventas_por_tienda(datos):
    calcular_promedio_ventas_por_tienda = np.mean(datos, axis=(0, 2))
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))

In [11]:
def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

In [12]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

In [14]:
def imprimir_resumen(ventas):
    pass

In [15]:
productos = 10
tiendas = 5
dias = 7

In [16]:
# Genera los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)
ventas = []
for producto in range(productos):
  for tienda in range(tiendas):
    for dia in range(dias):
      ventas_aleatorias = np.random.randint(0,100,[productos, tiendas, dias])
      ventas.append([producto, tienda, dia, ventas_aleatorias])
      print(ventas_aleatorias)

Se han truncado las últimas 5000 líneas del flujo de salida.
  [60 26 54 69 77 77 61]
  [21 87 24 10  8  2 61]]

 [[79 67 61  0 23 67 82]
  [43 39 28 87 88 19 58]
  [99 24  0 82 83 11  1]
  [33 51 86 42 54 52 58]
  [24 20 10 60 43  1 57]]

 [[ 0 18 90 25 46 95 45]
  [11  9 65  5 79 51 49]
  [38 11 90 84 97 68 93]
  [35  8 59 95 26  2 42]
  [21 87 31 12 19  9 19]]

 [[38 41 49  5 14 73  3]
  [59 12 13 78 75  5 40]
  [34 54 20 12 53 85 71]
  [10 13 28  1 32 65 96]
  [27 32 33 90 65  5 10]]

 [[97 54  6  8 59 99 71]
  [72 28 67 33 16 88 18]
  [23 71 19  8 39 78 26]
  [68 88  7 63 69 30 23]
  [ 5 22 88  3 25  7  3]]

 [[69 59 26 11 63 93 93]
  [88  4 59 64 39 65 18]
  [57 67 18 55 74  5 80]
  [ 3 93 62  0 84 97 11]
  [85 21 93 89 84 81 27]]

 [[80 58 85 86 28 77 96]
  [18 79 41 64  4 60 72]
  [15 60 66 23  0 79 42]
  [49 29 56 93 49 16 27]
  [62 19 40 88 36 56 37]]

 [[82 21 14 78  1 85 39]
  [93 40 55 22 37 88 48]
  [72  0 66 78 55 95  3]
  [89 93 87 52 94 67 46]
  [63 63 20 67 39 48 33]]

In [17]:
# Calcula los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

In [18]:
# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

In [19]:
# Imprime los resultados
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

Total de ventas por producto a lo largo de la semana: [1536 1760 1744 1863 1896 1776 1738 1714 1831 1496]
Total de ventas por tienda a lo largo de la semana: [3722 3334 3300 3558 3440]
Promedio de ventas por producto por día: [43.88571429 50.28571429 49.82857143 53.22857143 54.17142857 50.74285714
 49.65714286 48.97142857 52.31428571 42.74285714]
Promedio de ventas por tienda por día: [53.17142857 47.62857143 47.14285714 50.82857143 49.14285714]
Producto con mayor ventas: Producto 4
Producto con menor ventas: Producto 9
Tienda con mayor ventas: Tienda 0
Tienda con menor ventas: Tienda 2
